# Generated by Django 6.1.1 on 2026-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
